## Preprocessing

In [209]:
# Install modules if missing

#!pip install scikit-learn
#!pip install tensorflow
#!pip install keras-tuner

In [210]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head(50)

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
5,10556855,MINORITY ORGAN & TISSUE TRANSPLANT & EDUCATION...,T3,Independent,C1200,Preservation,Trust,1,0,N,5000,1
6,10558440,FRIENDS OF ARTS COUNCIL OF GREATER DENHAM SPRI...,T3,Independent,C1000,Preservation,Trust,1,100000-499999,N,31452,1
7,10566033,ISRAEL EMERGENCY ALLIANCE,T3,Independent,C2000,Preservation,Trust,1,10M-50M,N,7508025,1
8,10570430,ARAMCO BRATS INC,T7,Independent,C1000,ProductDev,Trust,1,1-9999,N,94389,1
9,10571689,INTERNATIONAL ASSOCIATION OF FIRE FIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
10,10573059,KAI ELUA OUTRIGGER CANOE CLUB,T3,Independent,C1200,Preservation,Trust,1,25000-99999,N,69656,0
11,10575727,HERITAGE ACADEMY,T3,Independent,C2000,Preservation,Trust,1,100000-499999,N,165593,0
12,10583569,THE UNITED STATES PONY CLUBS INC,T3,CompanySponsored,C1200,Preservation,Association,1,0,N,5000,1
13,10585206,DOMINION INTERNATIONAL NETWORK OF MINISTRIES &...,T3,Independent,C2700,Preservation,Trust,1,25000-99999,N,5301,1
14,10585443,V O W FOUNDATION,T3,Independent,C1000,Preservation,Trust,1,0,N,5000,1
15,10596727,JOSEPH E PEEBLES JR FOUNDATION,T3,Independent,C1200,Preservation,Trust,1,0,N,5000,1
16,10602428,WASHINGTON ASSOCIATION OF PHYSICIANS OF INDIAN...,T3,Independent,C2000,Preservation,Trust,1,0,N,5000,1
17,10603214,SAINT FRANCIS HOSPITAL SOUTH LLC,T3,Independent,C1000,Heathcare,Trust,1,50M+,N,86380556,0
18,10604986,ANCHORAGE COMMUNITY MENTAL HEALTH SERVICES,T3,CompanySponsored,C1000,Preservation,Trust,1,0,N,5000,0
19,10605038,HABITAT FOR HUMANITY INTERNATIONAL INC,T3,CompanySponsored,C1000,Preservation,Trust,1,100000-499999,N,376109,0
20,10608689,INTERNATIONAL FELINE SHOWCASE,T4,Independent,C3000,ProductDev,Trust,1,0,N,5000,1
21,10612407,METAMORPHASIS POWERHOUSE COMPANY,T3,Independent,C1200,Preservation,Trust,1,0,N,5000,1
22,10614724,REACH FOR EXCELLENCE INC,T3,Independent,C7000,Preservation,Trust,1,100000-499999,N,318296,0
23,10622557,INTERNATIONAL ASSOCIATION OF LIONS CLUB,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
24,10623527,SONS OF CONFEDERATE VETERANS INC,T3,CompanySponsored,C1200,Preservation,Trust,1,0,N,5000,0
25,10629331,MAGDALENA OLD TIMERS REUNION ASSOCIATION,T4,Independent,C3000,ProductDev,Trust,1,0,N,5000,1
26,10631060,INFRAGARD NATIONAL MEMBERS ALLIANCE INC,T3,CompanySponsored,C1000,Preservation,Trust,1,0,N,5000,1
27,10635952,POP WARNER LITTLE SCHOLARS INC,T3,CompanySponsored,C2000,Preservation,Trust,1,25000-99999,N,44004,1
28,10637680,FLORIDA STATE UNIVERSITY ALUMNI ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,0,N,5000,0
29,10637829,HAWAII TRAVEL & TOURISM RESEARCH ASSOCIATION,T6,Independent,C2000,ProductDev,Trust,1,0,N,5000,1
30,10637920,MEDICAL STAFF OF PARKVIEW COMMUNITY HOSPITAL M...,T6,Independent,C2000,ProductDev,Trust,1,100000-499999,N,323466,1
31,10638860,CLEAR UP SKIN CARE,T3,Independent,C1200,Preservation,Trust,1,0,N,5000,1
32,10639038,STAR TOURING AND RIDING SACARMENTO CHAPTER 153,T7,Independent,C1000,ProductDev,Trust,1,0,N,5000,1
33,10641003,SHERIFFS COMMUNITY ORGANIZED POLICING EFFORTS,T3,CompanySponsored,C1000,Preservation,Trust,1,0,N,5000,1
34,10642634,DOCTORS OFFERING CHARITABLE SERVICES,T3,Independent,C1000,Preservation,Trust,1,0,N,5000,0
35,10648919,G A P MINISTRIES,T3,Independent,C1200,Preservation,Trust,1,0,N,5000,0
36,10655941,MELLOWTONES BIG BAND INC,T4,Independent,C1000,ProductDev,Trust,1,0,N,5000,1
37,10656131,SAI HUMANITARIAN INSTITUTE OF LEARNING AND HEA...,T3,Independent,C1000,Preservation,Trust,1,0,N,5000,1
38,10656251,RIVERVIEW 2,T7,Independent,C1000,ProductDev,Association,1,0,N,5000,0
39,10656605,ERASTO R BATONGMALAQUE FOUNDATION,T3,Independent,C1000,Preservation,Trust,1,25000-99999,N,5000,1
40,10662680,TIFTON JUDICIAL CIRCUIT SHELTER INC,T3,Independent,C1000,Preservation,Trust,1,25000-99999,N,709815,0
41,10664127,IBEW LOCAL 180 HOLDING COMPANY,T2,Independent,C1000,ProductDev,Trust,1,25000-99999,N,1329410,0
42,10669807,ORLANDO PARROT HEADS OF CENTRAL FLORIDA INC,T7,Independent,C1000,ProductDev,Trust,1,0,N,5000,1
43,10671224,HABITAT FOR HUMANITY INTERNATIONAL INC,T3,CompanySponsored,C1000,Preservation,Trust,1,0,N,5000,0
44,10672368,HOLY SPIRIT CHURCH AND INSTITUTE INC,T3,Independent,C7200,Preservation,Trust,1,0,N,5000,1
45,10681022,K-9 SEARCH AND RESCUE OF ORANGE CITY INC,T3,Independent,C1000,Preservation,Trust,1,0,N,5000,1
46,10681362,PTA TEXAS CONGRESS,T3,CompanySponsored,C2000,Preservation,Trust,1,0,N,5000,0
47,10687111,SOUTHERN CALIFORNIA NATURIST ASSOCIATION,T7,Independent,C1000,ProductDev,Trust,1,0,N,5000,0
48,10691782,MOSES SONG MINISTRIES,T3,Independent,C1700,Preservation,Trust,1,0,N,5000,1
49,10692183,VINCI PARK HOME AND SCHOOL CLUB,T3,Independent,C1000,Preservation,Trust,1,0,N,5000,0

In [211]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN', 'NAME'])

In [212]:
# Determine the number of unique values in each column.
print(application_df.nunique())

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [213]:
# Look at APPLICATION_TYPE value counts for binning
app_type_value_counts = application_df['APPLICATION_TYPE'].value_counts()
app_type_value_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [214]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_val = 1000
application_types_to_replace = [app_type for app_type, count in app_type_value_counts.items() if count <= cutoff_val]

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
Other     2266
T4        1542
T6        1216
T5        1173
T19       1065
Name: count, dtype: int64

In [215]:
# Look at CLASSIFICATION value counts for binning
classification_value_counts = application_df['CLASSIFICATION'].value_counts()
classification_value_counts[:50]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
C2190        1
C4200        1
C2600        1
C5200        1
C1370        1
Name: count, dtype: int64

In [216]:
# You may find it helpful to look at CLASSIFICATION value counts >1
counts_greater_than_1 = classification_value_counts[classification_value_counts > 1]
print(counts_greater_than_1)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [217]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_val2 = 100
classifications_to_replace = [cls_type for cls_type, count in classification_value_counts.items() if count <= cutoff_val2]

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: count, dtype: int64

In [218]:
# Bin 'ASK_AMT' column

# Check the number range of the column
print(application_df['ASK_AMT'].min())
print(application_df['ASK_AMT'].max())

# Define the bin edges
bins =  [0,  1000,   10000,   100000,   1000000,   10000000,    100000000, 1000000000, 10000000000]
labels = ['0-1000', '1000-10000', '10000-100000', '100000-1000000', '1000000-10000000', '10000000-100000000', '100000000-1000000000', '1000000000-10000000000']

application_df['ASK_AMT'] = pd.cut(application_df['ASK_AMT'], bins, labels = labels)

application_df.head()

5000
8597806340

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,Other,Independent,C1000,ProductDev,Association,1,0,N,1000-10000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,100000-1000000,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,1000-10000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,1000-10000,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,100000-1000000,1

In [219]:
# Convert categorical data to numeric with `pd.get_dummies`
columns_to_encode = ['AFFILIATION', 'USE_CASE', 'ORGANIZATION', 'APPLICATION_TYPE', 'CLASSIFICATION', 'INCOME_AMT','ASK_AMT']
enc_app_df = pd.get_dummies(application_df, columns = columns_to_encode, dtype = int)
enc_app_df.head()

,STATUS,SPECIAL_CONSIDERATIONS,IS_SUCCESSFUL,AFFILIATION_CompanySponsored,AFFILIATION_Family/Parent,AFFILIATION_Independent,AFFILIATION_National,AFFILIATION_Other,AFFILIATION_Regional,USE_CASE_CommunityServ,...,INCOME_AMT_50M+,INCOME_AMT_5M-10M,ASK_AMT_0-1000,ASK_AMT_1000-10000,ASK_AMT_10000-100000,ASK_AMT_100000-1000000,ASK_AMT_1000000-10000000,ASK_AMT_10000000-100000000,ASK_AMT_100000000-1000000000,ASK_AMT_1000000000-10000000000
0,1,N,1,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,1,N,1,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,1,N,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,1,N,1,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,1,N,1,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [220]:
# Split our preprocessed data into our features and target arrays
y = enc_app_df['IS_SUCCESSFUL'].values
X = enc_app_df.drop(columns = ['IS_SUCCESSFUL', 'STATUS', 'SPECIAL_CONSIDERATIONS']).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 71, stratify = y)

In [221]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [222]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
print(number_input_features)
hidden_nodes_layer1 = 32
hidden_nodes_layer2 = 16
# hidden_nodes_layer3 = 8

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense
    (
    units = hidden_nodes_layer1, 
    activation = 'relu', 
    input_dim = number_input_features
    )
)

#nn.add(tf.keras.layers.Dropout(.2))

# Second hidden layer
nn.add(tf.keras.layers.Dense
    (
    units = hidden_nodes_layer2, 
    activation = 'sigmoid'
    )
)
#nn.add(tf.keras.layers.BatchNormalization(synchronized=True))

# Third hidden layer
# nn.add(tf.keras.layers.Dense
#     (
#     units = hidden_nodes_layer3, 
#     activation = 'relu'
#     )
# )

# Output layer
nn.add(tf.keras.layers.Dense
    (
    units = 1, 
    activation = 'sigmoid'
    )
)

# Check the structure of the model
nn.summary()

50

/opt/homebrew/lib/python3.11/site-packages/keras/src/layers/core/dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_39 (Dense)                │ (None, 32)             │         1,632 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_40 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_41 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,177 (8.50 KB)

 Trainable params: 2,177 (8.50 KB)

 Non-trainable params: 0 (0.00 B)

In [223]:
# Compile the model
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [224]:
# Train the model
model_fit = nn.fit(X_train_scaled, y_train, epochs = 50, batch_size=8)

Epoch 1/50

3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 244us/step - accuracy: 0.6919 - loss: 0.5973
Epoch 2/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 240us/step - accuracy: 0.7226 - loss: 0.5603
Epoch 3/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 237us/step - accuracy: 0.7320 - loss: 0.5511
Epoch 4/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 235us/step - accuracy: 0.7295 - loss: 0.5526
Epoch 5/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 239us/step - accuracy: 0.7305 - loss: 0.5489
Epoch 6/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 238us/step - accuracy: 0.7317 - loss: 0.5473
Epoch 7/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 245us/step - accuracy: 0.7344 - loss: 0.5451
Epoch 8/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 243us/step - accuracy: 0.7308 - loss: 0.5476
Epoch 9/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 256us/step - accuracy: 0.7362 - loss: 0.5442
Epoch 10/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 252us/step - accuracy: 0.7293 - loss: 0.5474
Epoch 11/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 270us/step - accuracy: 0.7364 - loss: 0.5412
Epoch 12/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 238us/step - accuracy: 0.7306 - loss: 0.5437
Epoch 13/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 237us/step - accuracy: 0.7309 - loss: 0.5464
Epoch 14/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 235us/step - accuracy: 0.7353 - loss: 0.5430
Epoch 15/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 235us/step - accuracy: 0.7345 - loss: 0.5411
Epoch 16/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 254us/step - accuracy: 0.7321 - loss: 0.5441
Epoch 17/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 248us/step - accuracy: 0.7347 - loss: 0.5423
Epoch 18/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 237us/step - accuracy: 0.7377 - loss: 0.5412
Epoch 19/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 237us/step - accuracy: 0.7366 - loss: 0.5387
Epoch 20/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 238us/step - accuracy: 0.7379 - loss: 0.5388
Epoch 21/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 241us/step - accuracy: 0.7395 - loss: 0.5380
Epoch 22/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 235us/step - accuracy: 0.7298 - loss: 0.5433
Epoch 23/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 254us/step - accuracy: 0.7342 - loss: 0.5388
Epoch 24/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 248us/step - accuracy: 0.7410 - loss: 0.5347
Epoch 25/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 270us/step - accuracy: 0.7382 - loss: 0.5380
Epoch 26/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 266us/step - accuracy: 0.7343 - loss: 0.5402
Epoch 27/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 279us/step - accuracy: 0.7372 - loss: 0.5384
Epoch 28/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 253us/step - accuracy: 0.7352 - loss: 0.5385
Epoch 29/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 264us/step - accuracy: 0.7327 - loss: 0.5406
Epoch 30/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 248us/step - accuracy: 0.7423 - loss: 0.5317
Epoch 31/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 236us/step - accuracy: 0.7407 - loss: 0.5354
Epoch 32/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 241us/step - accuracy: 0.7379 - loss: 0.5348
Epoch 33/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 234us/step - accuracy: 0.7397 - loss: 0.5333
Epoch 34/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 246us/step - accuracy: 0.7338 - loss: 0.5415
Epoch 35/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 246us/step - accuracy: 0.7428 - loss: 0.5332
Epoch 36/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 240us/step - accuracy: 0.7415 - loss: 0.5322
Epoch 37/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 239us/step - accuracy: 0.7402 - loss: 0.5354
Epoch 38/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 235us/step - accuracy: 0.7391 - loss: 0.5331
Epoch 39/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 242us/step - accuracy: 0.7451 - loss: 0.5342
Epoch 40/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 238us/step - accuracy: 0.7391 - loss: 0.5355
Epoch 41/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 260us/step - accuracy: 0.7382 - loss: 0.5378
Epoch 42/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 237us/step - accuracy: 0.7442 - loss: 0.5306
Epoch 43/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 236us/step - accuracy: 0.7395 - loss: 0.5335
Epoch 44/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 236us/step - accuracy: 0.7421 - loss: 0.5333
Epoch 45/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 234us/step - accuracy: 0.7432 - loss: 0.5306
Epoch 46/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 241us/step - accuracy: 0.7362 - loss: 0.5364
Epoch 47/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 234us/step - accuracy: 0.7381 - loss: 0.5355
Epoch 48/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 242us/step - accuracy: 0.7363 - loss: 0.5375
Epoch 49/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 239us/step - accuracy: 0.7412 - loss: 0.5324
Epoch 50/50
3216/3216 ━━━━━━━━━━━━━━━━━━━━ 1s 236us/step - accuracy: 0.7391 - loss: 0.5339

In [225]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 330us/step - accuracy: 0.7294 - loss: 0.5561
Loss: 0.5561277270317078, Accuracy: 0.7294460535049438

In [226]:
# Export our model to HDF5 file
from tensorflow.keras.models import load_model
nn.save('AlphabetSoupCharity_Optimization.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.